In [1]:
import pickle
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import sklearn
plt.style.use('ggplot')  # sets up pretty plots
%matplotlib inline
pd.set_option('display.max_rows', 2000)
pd.set_option('display.max_columns', 500)

In [2]:
df = pd.read_pickle('clean_data.pkl')

In [3]:
df.head()

Name RegistryCountry CountryofOwner  \
0                    Aalto-1       NR (10/17)        Finland   
1                    AAUSat-4      NR (12/16)        Denmark   
2    ABS-2 (Koreasat-8, ST-3)              NR  Multinational   
3                      ABS-2A      NR (12/16)  Multinational   
4  ABS-3 (Agila 2, Mabuhay 1)     Philippines  Multinational   

                  Operator/Owner       Users                 Purpose  \
0            University of Aalto       Civil  Technology Development   
1          University of Aalborg       Civil       Earth Observation   
2  Asia Broadcast Satellite Ltd.  Commercial          Communications   
3  Asia Broadcast Satellite Ltd.  Commercial          Communications   
4  Asia Broadcast Satellite Ltd.  Commercial          Communications   

  ClassofOrbit      TypeofOrbit  Longitude of GEO (degrees)  Perigee(km)  \
0          LEO              NaN                        0.00          497   
1          LEO  Sun-Synchronous                        0.00          442   
2          GEO              NaN                       75.00        35778   
3          GEO              NaN                      -75.00        35700   
4          GEO              NaN                      146.06        35769   

   Apogee(km)  Eccentricity  Inclination(degrees) Period(minutes)  \
0         517      0.001454                 97.45            94.7   
1         687      0.017665                 98.20            95.9   
2       35793      0.000178                  0.08         1436.03   
3       35700      0.000000                  0.00          1436.1   
4       35802      0.000391                  0.05         1436.07   

  LaunchMass(kg) DryMass(kg) Power(W) DateofLaunch ExpectedLifetime  \
0            4.5         NaN      4.5   2017-06-23           2 yrs.   
1              1         NaN      NaN   2016-04-25              NaN   
2           6330         NaN    16000   2014-02-06          15 yrs.   
3           1800         NaN      NaN   2016-06-15          15 yrs.   
4           3775        1800     9000   1997-08-19          15 yrs.   

                 Contractor CountryofContractor  \
0       University of Aalto             Finland   
1     University of Aalborg             Denmark   
2       Space Systems/Loral                 USA   
3  Boeing Satellite Systems                 USA   
4       Space Systems/Loral                 USA   

                        LaunchSite    LaunchVehicle    COSPAR#  NORAD#  
0       Satish Dhawan Space Centre             PSLV  2017-036L   42775  
1              Guiana Space Center       Soyuz 2.1a  2016-025E   41460  
2              Guiana Space Center    Ariane  5 ECA  2014-006A   39508  
3                   Cape Canaveral         Falcon 9  2016-038A   41588  
4  Xichang Satellite Launch Center  Long March CZ3B  1997-042A   24901

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1732 entries, 0 to 1737
Data columns (total 25 columns):
Name                          1732 non-null object
RegistryCountry               1732 non-null object
CountryofOwner                1732 non-null object
Operator/Owner                1732 non-null object
Users                         1732 non-null object
Purpose                       1732 non-null object
ClassofOrbit                  1732 non-null object
TypeofOrbit                   1180 non-null object
Longitude of GEO (degrees)    1721 non-null float64
Perigee(km)                   1732 non-null int64
Apogee(km)                    1732 non-null int64
Eccentricity                  1732 non-null float64
Inclination(degrees)          1732 non-null float64
Period(minutes)               1732 non-null object
LaunchMass(kg)                1620 non-null object
DryMass(kg)                   475 non-null object
Power(W)                      645 non-null object
DateofLaunch               

Predict the puprose of the satellite.
I am only using the numerical values to predict the purpose of the satellite

In [5]:
df1 = pd.DataFrame(data=df, columns = ['Purpose','Longitude of GEO (degrees)','Perigee(km)', 'Apogee(km)', 'Eccentricity', 'Inclination(degrees)', 'Period(minutes)', 'LaunchMass(kg)'])

In [6]:
df1.head()

Purpose  Longitude of GEO (degrees)  Perigee(km)  \
0  Technology Development                        0.00          497   
1       Earth Observation                        0.00          442   
2          Communications                       75.00        35778   
3          Communications                      -75.00        35700   
4          Communications                      146.06        35769   

   Apogee(km)  Eccentricity  Inclination(degrees) Period(minutes)  \
0         517      0.001454                 97.45            94.7   
1         687      0.017665                 98.20            95.9   
2       35793      0.000178                  0.08         1436.03   
3       35700      0.000000                  0.00          1436.1   
4       35802      0.000391                  0.05         1436.07   

  LaunchMass(kg)  
0            4.5  
1              1  
2           6330  
3           1800  
4           3775

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1732 entries, 0 to 1737
Data columns (total 8 columns):
Purpose                       1732 non-null object
Longitude of GEO (degrees)    1721 non-null float64
Perigee(km)                   1732 non-null int64
Apogee(km)                    1732 non-null int64
Eccentricity                  1732 non-null float64
Inclination(degrees)          1732 non-null float64
Period(minutes)               1732 non-null object
LaunchMass(kg)                1620 non-null object
dtypes: float64(3), int64(2), object(3)
memory usage: 121.8+ KB


In [8]:
df1.dropna(inplace=True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1609 entries, 0 to 1737
Data columns (total 8 columns):
Purpose                       1609 non-null object
Longitude of GEO (degrees)    1609 non-null float64
Perigee(km)                   1609 non-null int64
Apogee(km)                    1609 non-null int64
Eccentricity                  1609 non-null float64
Inclination(degrees)          1609 non-null float64
Period(minutes)               1609 non-null object
LaunchMass(kg)                1609 non-null object
dtypes: float64(3), int64(2), object(3)
memory usage: 113.1+ KB


In [64]:
X = pd.DataFrame(data=df1, columns = ['Longitude of GEO (degrees)','Perigee(km)', 'Apogee(km)', 'Eccentricity', 'Inclination(degrees)', 'Period(minutes)', 'LaunchMass(kg)'])
#y = pd.DataFrame(data=df1, columns = ['Purpose'])
y = np.array(df1.Purpose)
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1609 entries, 0 to 1737
Data columns (total 7 columns):
Longitude of GEO (degrees)    1609 non-null float64
Perigee(km)                   1609 non-null int64
Apogee(km)                    1609 non-null int64
Eccentricity                  1609 non-null float64
Inclination(degrees)          1609 non-null float64
Period(minutes)               1609 non-null object
LaunchMass(kg)                1609 non-null object
dtypes: float64(3), int64(2), object(2)
memory usage: 100.6+ KB


In [65]:
X['Period(minutes)'].unique()

array([94.7, 95.9, 1436.03, 1436.1, 1436.07, 1436, 1436.08, 1436.06,
       1436.14, 1438.8, 1437.19, 97.4, 97.5, 97.6, 98, 97.74, 97.88,
       95.19, 96.23, 1436.09, 96.2, 97.76, 97.2, 97.27, 96.06, 94.18,
       94.5, 97.7, 98.4, 98.3, 98.2, 92.6, 1436.05, 1436.24, 1436.12,
       114.9, 96.99, 92.61, 99.4, 100.3, 97, 97.8, 97.17, 97.99, 1440.31,
       1436.01, 97.71, 1436.11, 1436.17, 1436.15, 94.75, 1436.04, 1438.2,
       1434.1, 1436.26, 97.54, 95.46, 96.7, 1439.76, 1427.27, 96.1, 99,
       96.01, 773.19, 773.21, 773.1, 1435.92, 1461.81, 1435.73, 773.2,
       773.3, 1435.82, 1435.93, 1435.1, 773.39, 98.6, 94.6, 94.8, 1436.2,
       98.27, 99.6, 97.1, 1365.61, 96.55, 98.8, 98.26, 97.72, 91.34,
       103.11, 99.67, 97.66, 96.29, 94.76, 95.5, 3808.92, 98.87, 98.5,
       100.7, 100.74, 96.43, 95.07, 96.05, 96, 96.6, 101.5, 100.9, 98.9,
       95.6, 99.2, 92.4, 95.16, 95.13, 95.1, 95.15, 95.12, 97.36, 94.54,
       96.85, 96.8, 93.7, 96.4, 1443.51, 1434.07, 97.69, 101.9, 101.8,


In [66]:
X['Period(minutes)'].replace({'8 days':11520}, inplace=True) #Change '8 days' to its equivalent in minutes(11520)'
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1609 entries, 0 to 1737
Data columns (total 7 columns):
Longitude of GEO (degrees)    1609 non-null float64
Perigee(km)                   1609 non-null int64
Apogee(km)                    1609 non-null int64
Eccentricity                  1609 non-null float64
Inclination(degrees)          1609 non-null float64
Period(minutes)               1609 non-null float64
LaunchMass(kg)                1609 non-null object
dtypes: float64(4), int64(2), object(1)
memory usage: 100.6+ KB


In [67]:
X['LaunchMass(kg)'].unique()

array([4.5, 1, 6330, 1800, 3775, 2000, 4143, 2894, 3500, 4500, 5000, 6169,
       3, 5, 1.5, 2, 3460, 2704, 215, 14, 6, 53, 531, 1.7, 6650, 117, 103,
       10, 130, 5465, 6265, 2938, 2783, 2315, 2340, 4200, 4312, 2081,
       2648, 2500, 2845, 3909, 3901, 1935, 2015, 29, 4710, 5910, 4715,
       4905, 12, 4680, 5054, 5200, 3000, 4630, 3600, 2977, 3105, 3480,
       4137, 3760, 3700, 3813, 2775, 500, 2924, 3010, 3379, 3690, 4332,
       5345, 5350, 3635, 3315, 3643, 1420, 6052, 6000, 1500, 5471, 5724,
       230, 3080, 25, 3250, 3304, 5420, 4940, 3400, 5500, 4000, 2200,
       3800, 800, 2300, 166, 5223, 92, 400, 44, 1780, 2495, 3540, 1980,
       2060, 2910, 3669, 587, 7, 15, 1560, 680, 694, 727, 714, 712, 490,
       91, 159, 4, 4742, 50, 5100, 4600, 100, 100.8, 200, 5585, 3.15, 848,
       2460, 2440, 817, 11, 70, 1700, 720, 2120, 1850, 90, 310, 6.5, 8,
       5900, 3420, 4300, 5483, 45, 447, 1134, 1152, 1154, 1155, 2650,
       1156, 2380, 300, 27, 3287, 4333, 4328, 6384, 5521, 665

In [68]:
X['LaunchMass(kg)'].replace({'5,000+':5000}, inplace=True) #Change '5000+' to 5000
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1609 entries, 0 to 1737
Data columns (total 7 columns):
Longitude of GEO (degrees)    1609 non-null float64
Perigee(km)                   1609 non-null int64
Apogee(km)                    1609 non-null int64
Eccentricity                  1609 non-null float64
Inclination(degrees)          1609 non-null float64
Period(minutes)               1609 non-null float64
LaunchMass(kg)                1609 non-null float64
dtypes: float64(5), int64(2)
memory usage: 100.6 KB


In [69]:
print(y)

['Technology Development' 'Earth Observation' 'Communications' ...
 'Earth Observation' 'Earth Observation' 'Earth Observation']


In [70]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y)

LabelEncoder()

In [71]:
list(le.classes_)

['Communications',
 'Earth Observation',
 'Earth Science',
 'Multipurpose',
 'Navigation',
 'Space Observation',
 'Space Science',
 'Technology Demonstration',
 'Technology Development']

In [72]:
encoded_y = le.transform(y)
print(encoded_y)

[8 1 0 ... 1 1 1]


In [73]:
len(encoded_y)

1609

In [74]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, encoded_y, test_size =0.3, random_state=0, stratify=encoded_y)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

knn.score(X_test, y_test)

0.8136645962732919

## Logistic Regression 

In [20]:
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [21]:
df1.head()

Purpose  Longitude of GEO (degrees)  Perigee(km)  \
0  Technology Development                        0.00          497   
1       Earth Observation                        0.00          442   
2          Communications                       75.00        35778   
3          Communications                      -75.00        35700   
4          Communications                      146.06        35769   

   Apogee(km)  Eccentricity  Inclination(degrees) Period(minutes)  \
0         517      0.001454                 97.45            94.7   
1         687      0.017665                 98.20            95.9   
2       35793      0.000178                  0.08         1436.03   
3       35700      0.000000                  0.00          1436.1   
4       35802      0.000391                  0.05         1436.07   

  LaunchMass(kg)  
0            4.5  
1              1  
2           6330  
3           1800  
4           3775

In [22]:
# Split the data into a training and test set.
Xlr, Xtestlr, ylr, ytestlr = train_test_split(X, encoded_y, random_state=5)

clf = LogisticRegression()
# Fit the model on the trainng data.
clf.fit(Xlr, ylr)
# Print the accuracy from the testing data.
print(accuracy_score(clf.predict(Xtestlr), ytestlr))

0.6253101736972705


## Use full data frame 'df'

In [23]:
df.head()

Name RegistryCountry CountryofOwner  \
0                    Aalto-1       NR (10/17)        Finland   
1                    AAUSat-4      NR (12/16)        Denmark   
2    ABS-2 (Koreasat-8, ST-3)              NR  Multinational   
3                      ABS-2A      NR (12/16)  Multinational   
4  ABS-3 (Agila 2, Mabuhay 1)     Philippines  Multinational   

                  Operator/Owner       Users                 Purpose  \
0            University of Aalto       Civil  Technology Development   
1          University of Aalborg       Civil       Earth Observation   
2  Asia Broadcast Satellite Ltd.  Commercial          Communications   
3  Asia Broadcast Satellite Ltd.  Commercial          Communications   
4  Asia Broadcast Satellite Ltd.  Commercial          Communications   

  ClassofOrbit      TypeofOrbit  Longitude of GEO (degrees)  Perigee(km)  \
0          LEO              NaN                        0.00          497   
1          LEO  Sun-Synchronous                        0.00          442   
2          GEO              NaN                       75.00        35778   
3          GEO              NaN                      -75.00        35700   
4          GEO              NaN                      146.06        35769   

   Apogee(km)  Eccentricity  Inclination(degrees) Period(minutes)  \
0         517      0.001454                 97.45            94.7   
1         687      0.017665                 98.20            95.9   
2       35793      0.000178                  0.08         1436.03   
3       35700      0.000000                  0.00          1436.1   
4       35802      0.000391                  0.05         1436.07   

  LaunchMass(kg) DryMass(kg) Power(W) DateofLaunch ExpectedLifetime  \
0            4.5         NaN      4.5   2017-06-23           2 yrs.   
1              1         NaN      NaN   2016-04-25              NaN   
2           6330         NaN    16000   2014-02-06          15 yrs.   
3           1800         NaN      NaN   2016-06-15          15 yrs.   
4           3775        1800     9000   1997-08-19          15 yrs.   

                 Contractor CountryofContractor  \
0       University of Aalto             Finland   
1     University of Aalborg             Denmark   
2       Space Systems/Loral                 USA   
3  Boeing Satellite Systems                 USA   
4       Space Systems/Loral                 USA   

                        LaunchSite    LaunchVehicle    COSPAR#  NORAD#  
0       Satish Dhawan Space Centre             PSLV  2017-036L   42775  
1              Guiana Space Center       Soyuz 2.1a  2016-025E   41460  
2              Guiana Space Center    Ariane  5 ECA  2014-006A   39508  
3                   Cape Canaveral         Falcon 9  2016-038A   41588  
4  Xichang Satellite Launch Center  Long March CZ3B  1997-042A   24901

In [24]:
country_list = np.array(df['CountryofOwner'])
users_list = np.array(df['Users'])
purpose_list = np.array(df['Purpose'])
classoforbit_list = np.array(df['ClassofOrbit'])

In [25]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [26]:
le.fit(purpose_list)
encoded_purpose = le.transform(purpose_list)
len(encoded_purpose)

1732

In [27]:
dummy_countries = pd.get_dummies(country_list)
dummy_users = pd.get_dummies(users_list)
dummy_classoforbit = pd.get_dummies(classoforbit_list)

In [28]:
df_dummies = dummy_countries.join(dummy_users).join(dummy_classoforbit).join(pd.DataFrame(encoded_purpose))

In [29]:
df_dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1732 entries, 0 to 1731
Data columns (total 77 columns):
Algeria                           1732 non-null uint8
Argentina                         1732 non-null uint8
Australia                         1732 non-null uint8
Austria                           1732 non-null uint8
Azerbaijan                        1732 non-null uint8
Bangladesh                        1732 non-null uint8
Belarus                           1732 non-null uint8
Belgium                           1732 non-null uint8
Bolivia                           1732 non-null uint8
Brazil                            1732 non-null uint8
Bulgaria                          1732 non-null uint8
Canada                            1732 non-null uint8
Chile                             1732 non-null uint8
China                             1732 non-null uint8
Czech Republic                    1732 non-null uint8
Denmark                           1732 non-null uint8
ESA                          

In [30]:
df['Purpose']

0         Technology Development
1              Earth Observation
2                 Communications
3                 Communications
4                 Communications
5                 Communications
6                 Communications
7                 Communications
8                 Communications
9              Earth Observation
10             Earth Observation
11             Earth Observation
12             Earth Observation
13             Earth Observation
14             Earth Observation
15                Communications
16                Communications
17        Technology Development
18        Technology Development
19        Technology Development
20        Technology Development
21        Technology Development
22        Technology Development
23        Technology Development
24        Technology Development
25        Technology Development
26        Technology Development
27        Technology Development
28        Technology Development
29        Technology Development
30        

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1732 entries, 0 to 1737
Data columns (total 25 columns):
Name                          1732 non-null object
RegistryCountry               1732 non-null object
CountryofOwner                1732 non-null object
Operator/Owner                1732 non-null object
Users                         1732 non-null object
Purpose                       1732 non-null object
ClassofOrbit                  1732 non-null object
TypeofOrbit                   1180 non-null object
Longitude of GEO (degrees)    1721 non-null float64
Perigee(km)                   1732 non-null int64
Apogee(km)                    1732 non-null int64
Eccentricity                  1732 non-null float64
Inclination(degrees)          1732 non-null float64
Period(minutes)               1732 non-null object
LaunchMass(kg)                1620 non-null object
DryMass(kg)                   475 non-null object
Power(W)                      645 non-null object
DateofLaunch               

In [32]:
df2 = df.merge(df_dummies, left_index=True, right_index=True)
df2.head()

Name RegistryCountry CountryofOwner  \
0                    Aalto-1       NR (10/17)        Finland   
1                    AAUSat-4      NR (12/16)        Denmark   
2    ABS-2 (Koreasat-8, ST-3)              NR  Multinational   
3                      ABS-2A      NR (12/16)  Multinational   
4  ABS-3 (Agila 2, Mabuhay 1)     Philippines  Multinational   

                  Operator/Owner       Users                 Purpose  \
0            University of Aalto       Civil  Technology Development   
1          University of Aalborg       Civil       Earth Observation   
2  Asia Broadcast Satellite Ltd.  Commercial          Communications   
3  Asia Broadcast Satellite Ltd.  Commercial          Communications   
4  Asia Broadcast Satellite Ltd.  Commercial          Communications   

  ClassofOrbit      TypeofOrbit  Longitude of GEO (degrees)  Perigee(km)  \
0          LEO              NaN                        0.00          497   
1          LEO  Sun-Synchronous                        0.00          442   
2          GEO              NaN                       75.00        35778   
3          GEO              NaN                      -75.00        35700   
4          GEO              NaN                      146.06        35769   

   Apogee(km)  Eccentricity  Inclination(degrees) Period(minutes)  \
0         517      0.001454                 97.45            94.7   
1         687      0.017665                 98.20            95.9   
2       35793      0.000178                  0.08         1436.03   
3       35700      0.000000                  0.00          1436.1   
4       35802      0.000391                  0.05         1436.07   

  LaunchMass(kg) DryMass(kg) Power(W) DateofLaunch ExpectedLifetime  \
0            4.5         NaN      4.5   2017-06-23           2 yrs.   
1              1         NaN      NaN   2016-04-25              NaN   
2           6330         NaN    16000   2014-02-06          15 yrs.   
3           1800         NaN      NaN   2016-06-15          15 yrs.   
4           3775        1800     9000   1997-08-19          15 yrs.   

                 Contractor CountryofContractor  \
0       University of Aalto             Finland   
1     University of Aalborg             Denmark   
2       Space Systems/Loral                 USA   
3  Boeing Satellite Systems                 USA   
4       Space Systems/Loral                 USA   

                        LaunchSite    LaunchVehicle    COSPAR#  NORAD#  \
0       Satish Dhawan Space Centre             PSLV  2017-036L   42775   
1              Guiana Space Center       Soyuz 2.1a  2016-025E   41460   
2              Guiana Space Center    Ariane  5 ECA  2014-006A   39508   
3                   Cape Canaveral         Falcon 9  2016-038A   41588   
4  Xichang Satellite Launch Center  Long March CZ3B  1997-042A   24901   

   Algeria  Argentina  Australia  Austria  Azerbaijan  Bangladesh  Belarus  \
0        0          0          0        0           0           0        0   
1        0          0          0        0           0           0        0   
2        0          0          0        0           0           0        0   
3        0          0          0        0           0           0        0   
4        0          0          0        0           0           0        0   

   Belgium  Bolivia  Brazil  Bulgaria  Canada  Chile  China  Czech Republic  \
0        0        0       0         0       0      0      0               0   
1        0        0       0         0       0      0      0               0   
2        0        0       0         0       0      0      0               0   
3        0        0       0         0       0      0      0               0   
4        0        0       0         0       0      0      0               0   

   Denmark  ESA  Egypt  Finland  France  Germany  Greece  India  Indonesia  \
0        0    0      0        1       0        0       0      0          0   
1        1    0      0        0       0        0       0

In [33]:
df2.drop(columns=['Purpose','Name', 'RegistryCountry', 'CountryofOwner','Operator/Owner','Users','ClassofOrbit','TypeofOrbit','DryMass(kg)','Power(W)','DateofLaunch','ExpectedLifetime','Contractor', 'CountryofContractor','LaunchSite', 'LaunchVehicle','COSPAR#','NORAD#'], inplace=True)

In [34]:
df2.drop(columns = ['LaunchMass(kg)'], inplace=True)

In [35]:
df2.head()

Longitude of GEO (degrees)  Perigee(km)  Apogee(km)  Eccentricity  \
0                        0.00          497         517      0.001454   
1                        0.00          442         687      0.017665   
2                       75.00        35778       35793      0.000178   
3                      -75.00        35700       35700      0.000000   
4                      146.06        35769       35802      0.000391   

   Inclination(degrees) Period(minutes)  Algeria  Argentina  Australia  \
0                 97.45            94.7        0          0          0   
1                 98.20            95.9        0          0          0   
2                  0.08         1436.03        0          0          0   
3                  0.00          1436.1        0          0          0   
4                  0.05         1436.07        0          0          0   

   Austria  Azerbaijan  Bangladesh  Belarus  Belgium  Bolivia  Brazil  \
0        0           0           0        0        0        0       0   
1        0           0           0        0        0        0       0   
2        0           0           0        0        0        0       0   
3        0           0           0        0        0        0       0   
4        0           0           0        0        0        0       0   

   Bulgaria  Canada  Chile  China  Czech Republic  Denmark  ESA  Egypt  \
0         0       0      0      0               0        0    0      0   
1         0       0      0      0               0        1    0      0   
2         0       0      0      0               0        0    0      0   
3         0       0      0      0               0        0    0      0   
4         0       0      0      0               0        0    0      0   

   Finland  France  Germany  Greece  India  Indonesia  Iran  Iraq  Israel  \
0        1       0        0       0      0          0     0     0       0   
1        0       0        0       0      0          0     0     0       0   
2        0       0        0       0      0          0     0     0       0   
3        0       0        0       0      0          0     0     0       0   
4        0       0        0       0      0          0     0     0       0   

   Italy  Japan  Kazakhstan  Laos  Latvia  Lithuania  Luxembourg  Malaysia  \
0      0      0           0     0       0          0           0         0   
1      0      0           0     0       0          0           0         0   
2      0      0           0     0       0          0           0         0   
3      0      0           0     0       0          0           0         0   
4      0      0           0     0       0          0           0         0   

   Mexico  Mongolia  Multinational  Netherlands  Nigeria  Norway  Pakistan  \
0       0         0              0            0        0       0         0   
1       0         0              0            0        0       0         0   
2       0         0              1            0        0       0         0   
3       0         0              1            0        0       0         0   
4       0         0              1            0        0       0         0   

   Peru  Russia  Saudi Arabia  Singapore  Slovakia  South Africa  South Korea  \
0     0       0             0          0         0             0            0   
1     0       0             0          0         0             0            0   
2     0       0             0          0         0             0            0   
3     0       0             0          0         0             0            0   
4     0       0             0          0         0             0            0   

   Spain  Sweden  Switzerland  Taiwan  Thailand  Turkey  USA  Ukraine  \
0      0       0            0       0         0       0    0        0   
1      0       0            0       0         0       0    0        0   
2      0       0            0       0         0       0    0        0   
3      0       0            0       0         0       0    0 

In [36]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1726 entries, 0 to 1731
Data columns (total 83 columns):
Longitude of GEO (degrees)        1715 non-null float64
Perigee(km)                       1726 non-null int64
Apogee(km)                        1726 non-null int64
Eccentricity                      1726 non-null float64
Inclination(degrees)              1726 non-null float64
Period(minutes)                   1726 non-null object
Algeria                           1726 non-null uint8
Argentina                         1726 non-null uint8
Australia                         1726 non-null uint8
Austria                           1726 non-null uint8
Azerbaijan                        1726 non-null uint8
Bangladesh                        1726 non-null uint8
Belarus                           1726 non-null uint8
Belgium                           1726 non-null uint8
Bolivia                           1726 non-null uint8
Brazil                            1726 non-null uint8
Bulgaria              

In [37]:
df2.dropna(inplace=True)

In [38]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1715 entries, 0 to 1731
Data columns (total 83 columns):
Longitude of GEO (degrees)        1715 non-null float64
Perigee(km)                       1715 non-null int64
Apogee(km)                        1715 non-null int64
Eccentricity                      1715 non-null float64
Inclination(degrees)              1715 non-null float64
Period(minutes)                   1715 non-null object
Algeria                           1715 non-null uint8
Argentina                         1715 non-null uint8
Australia                         1715 non-null uint8
Austria                           1715 non-null uint8
Azerbaijan                        1715 non-null uint8
Bangladesh                        1715 non-null uint8
Belarus                           1715 non-null uint8
Belgium                           1715 non-null uint8
Bolivia                           1715 non-null uint8
Brazil                            1715 non-null uint8
Bulgaria              

In [39]:
df2['Period(minutes)'].replace({'8 days':11520}, inplace=True)

In [40]:
df2.rename(columns={0:'encoded_purpose'}, inplace=True)

In [41]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1715 entries, 0 to 1731
Data columns (total 83 columns):
Longitude of GEO (degrees)        1715 non-null float64
Perigee(km)                       1715 non-null int64
Apogee(km)                        1715 non-null int64
Eccentricity                      1715 non-null float64
Inclination(degrees)              1715 non-null float64
Period(minutes)                   1715 non-null float64
Algeria                           1715 non-null uint8
Argentina                         1715 non-null uint8
Australia                         1715 non-null uint8
Austria                           1715 non-null uint8
Azerbaijan                        1715 non-null uint8
Bangladesh                        1715 non-null uint8
Belarus                           1715 non-null uint8
Belgium                           1715 non-null uint8
Bolivia                           1715 non-null uint8
Brazil                            1715 non-null uint8
Bulgaria             

In [42]:
X2 = df2.drop(columns='encoded_purpose')
y2 = np.array(df2['encoded_purpose'])

## Logistic Regresion

In [59]:
# Split the data into a training and test set.
Xlr, Xtestlr, ylr, ytestlr = train_test_split(X2.iloc[:, 0:6], y2, random_state=5)

clf = LogisticRegression()
# Fit the model on the trainng data.
clf.fit(Xlr, ylr)
# Print the accuracy from the testing data.
print(accuracy_score(clf.predict(Xtestlr), ytestlr))

0.5314685314685315


## KNN Classification

In [100]:
X_train, X_test, y_train, y_test = train_test_split(X2, y2, test_size =0.33)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

knn.score(X_test, y_test)

0.7084805653710248

## Confusion Matrix and Classification Report

In [45]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[190  24   3   1   1   0   1   0  10]
 [ 29 131   0   0   1   0   2   0   5]
 [  1   1   0   0   0   0   0   0   3]
 [  5   2   0   1   0   0   0   0   1]
 [  6   0   0   0  21   0   0   0   0]
 [  2   0   0   0   0   0   0   0   0]
 [  8   5   1   0   0   0   3   0   3]
 [  2   2   0   0   0   0   0   0   1]
 [ 16  13   0   1   0   0   3   0  16]]
             precision    recall  f1-score   support

          0       0.73      0.83      0.78       230
          1       0.74      0.78      0.76       168
          2       0.00      0.00      0.00         5
          3       0.33      0.11      0.17         9
          4       0.91      0.78      0.84        27
          5       0.00      0.00      0.00         2
          6       0.33      0.15      0.21        20
          7       0.00      0.00      0.00         5
          8       0.41      0.33      0.36        49

avg / total       0.67      0.70      0.68       515



C:\Users\huzmu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## Feature Selection

In [46]:
knn=KNeighborsClassifier()

In [47]:
col_names = list(X2.columns.values)
print(col_names)

['Longitude of GEO (degrees)', 'Perigee(km)', 'Apogee(km)', 'Eccentricity', 'Inclination(degrees)', 'Period(minutes)', 'Algeria', 'Argentina', 'Australia', 'Austria', 'Azerbaijan', 'Bangladesh', 'Belarus', 'Belgium', 'Bolivia', 'Brazil', 'Bulgaria', 'Canada', 'Chile', 'China', 'Czech Republic', 'Denmark', 'ESA', 'Egypt', 'Finland', 'France', 'Germany', 'Greece', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Italy', 'Japan', 'Kazakhstan', 'Laos', 'Latvia', 'Lithuania', 'Luxembourg', 'Malaysia', 'Mexico', 'Mongolia', 'Multinational', 'Netherlands', 'Nigeria', 'Norway', 'Pakistan', 'Peru', 'Russia', 'Saudi Arabia', 'Singapore', 'Slovakia', 'South Africa', 'South Korea', 'Spain', 'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'USA', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'Uruguay', 'Venezuela', 'Vietnam', 'Civil', 'Commercial', 'Commercial/Government/Military', 'Government', 'Government/Civil', 'Government/Commercial', 'Military', 'Military/Civil', 'Military/Comm

In [57]:
from sklearn.model_selection import cross_val_score
print('Feature  Accuracy')
a = []
for i in col_names:
    X = np.array(X2[i]).reshape(-1, 1)
    scores = cross_val_score(knn, X, y2)
    print('%s        %g' % (i, scores.mean()))
    #print(scores.mean())

Feature  Accuracy
Longitude of GEO (degrees)        0.400615
Perigee(km)        0.555296
Apogee(km)        0.526976
Eccentricity        0.464327
Inclination(degrees)        0.556975
Period(minutes)        0.5344
Algeria        0.390066
Argentina        0.360733
Australia        0.385958
Austria        0.390066
Azerbaijan        0.390066
Bangladesh        0.390066
Belarus        0.390066
Belgium        0.390066
Bolivia        0.390066
Brazil        0.390066
Bulgaria        0.390066
Canada        0.342811
Chile        0.390066
China        0.409396
Czech Republic        0.390066
Denmark        0.390644
ESA        0.401676
Egypt        0.390066
Finland        0.390066
France        0.387144
Germany        0.356028
Greece        0.390066
India        0.362483
Indonesia        0.386551
Iran        0.390066
Iraq        0.390066
Israel        0.387746
Italy        0.362483
Japan        0.356041
Kazakhstan        0.390066
Laos        0.390066
Latvia        0.390066
Lithuania        0.390066
Lu

In [49]:
np.array(X2['Perigee(km)'])

array([  497,   442, 35778, ..., 35767, 35781, 35759], dtype=int64)

## GridSearchCV

In [93]:
# your turn
from sklearn.grid_search import GridSearchCV
knn=KNeighborsClassifier()
param_grid = {'n_neighbors': np.arange(3, 100, 10)}
knn_cv = GridSearchCV(knn, param_grid, cv=3, scoring='accuracy')
knn_cv.fit(X2, y2)
#fitmodel = GridSearchCV(clfl2, param_grid=parameters, cv=5, scoring="accuracy")
#fitmodel.fit(X2, y2)
#fitmodel.best_estimator_, fitmodel.best_params_, fitmodel.best_score_, fitmodel.grid_scores_

GridSearchCV(cv=3, error_score='raise',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_neighbors': array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])},
       pre_dispatch='2*n_jobs', refit=True, scoring='accuracy', verbose=0)

In [94]:
knn_cv.best_params_

{'n_neighbors': 43}

In [95]:
knn_cv.best_score_

0.6443148688046647

In [53]:
knn_cv.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=48, p=2,
           weights='uniform')

In [96]:
knn_cv.grid_scores_

[mean: 0.59592, std: 0.08172, params: {'n_neighbors': 3},
 mean: 0.57959, std: 0.07590, params: {'n_neighbors': 13},
 mean: 0.62157, std: 0.08083, params: {'n_neighbors': 23},
 mean: 0.63790, std: 0.07886, params: {'n_neighbors': 33},
 mean: 0.64431, std: 0.08849, params: {'n_neighbors': 43},
 mean: 0.63790, std: 0.08854, params: {'n_neighbors': 53},
 mean: 0.62507, std: 0.09977, params: {'n_neighbors': 63},
 mean: 0.62041, std: 0.10250, params: {'n_neighbors': 73},
 mean: 0.61691, std: 0.10769, params: {'n_neighbors': 83},
 mean: 0.61866, std: 0.10746, params: {'n_neighbors': 93}]